### PR TITLE
added language for roman latin

### PR DESCRIPTION
**Pull request by vtleavs**

### CODE REVIEW

**Comment by sognefej** [comment]
My changelog is breaking the repo...don't worry about it 
Why latin?

**Comment by takipsizad** [comment]
strange proably wrong language code

**Comment by sognefej** [comment]
Heck how do I re-run these tests? I think the CI/CD just lagged out trying to talk to the server and gave a false negative.

**Comment by sognefej** [comment]
Started the build check again should come back fine.

**Comment by sognefej** [comment]
https://github.com/actions/virtual-environments/issues/2247

I think their CI/CD servers are getting hit pretty hard.

**Comment by sognefej** [comment]
https://minecraft.gamepedia.com/Language

Everything looks fine....guess Plantus now supports latin.

**Review by sognefej — APPROVED** [review]

**Pull request merged**
